### ISSUE TITLE
from_cnv failed to read cnv files with both prDM and depSM variable

### ISSUE THREAD

**Issue by guillotp** [pyoceans/python-ctd#202]
I get the following error message "ValueError: Expected one pressure/depth column, got ['prDM', 'depSM']."
I removed the depSM variable from the file and run the from_cnv method again with no error.

**Comment by MDHDZ91** [comment]
Are you sure you are running the most up to date code? This was an issue I dealt with before and we pushed a new if statment that fixed the issue for me. The from_cnv function in read.py has an if statement so that if more than one key is found like in your case the first one will be used - make sure the scripts you have also have this update.

**Comment by MDHDZ91** [comment]
glad to hear that guillotp!

**Comment by ocefpaf** [comment]
Closing this as fixed. Thanks @guillotp for the report and @MDHDZ91 for answering it so quickly!
