### ISSUE TITLE
Create a "lighter" branch?

### ISSUE THREAD

**Issue by vinisalazar** [pyoceans/python-ctd#52]
Hi @ocefpaf, today I cloned this repo again to re-run some analyses, and noticed the enormous size of the tests/data/CTD/raw directory, I think the cloned repo amounted to almost 800mb, would you consider making a "lighter" branch available? I made one of my own in my fork of the repo, and just by deleting the "raw" directory, the repo size decreased substantially. However, I did not submit a PR to the master branch because I do not know the importance of these files to the integrity of the code.

I think for future users, having a branch which does not contain heavy data files would be useful. What do you think?

**Comment by ocefpaf** [comment]
Removing the files won't work b/c the they will be in the git history. Even if we prune them from the git history and push, GitHub forks will re-introduce them, so we must contact GH to ask then to "prune" it and everybody will need to re-fork it after that. This never really worked for me in the past b/c the files always ends up re-introduced due to someone's fork. I'll write GH and see if they have a newer better solution for this.

**Comment by vinisalazar** [comment]
I see. Thanks for clarifying that.
